baseurl = "https://progressivepartyofamerica.us" # Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
title = "Progressive Party of America"
theme = "hugo-universal-theme"
#themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[services]
[services.disqus]
# Enable comments by entering your Disqus shortname
Shortname = ""
[services.googleAnalytics]
# Enable Google Analytics by entering your tracking code
id = ""

[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

#[[menu.main]]
#    name       = "Platform"
#    url        = "/platform"
#    weight     = 1
#    parent     = "menu.home"

#[[menu.main]]
#    name       = "Option 2: Application"
#    url        = "/"
#    weight     = 2
#    parent     = "menu.home"

#[[menu.main]]
#    name       = "Option 3: Startup"
#    url        = "/"
#    weight     = 3
#    parent     = "menu.home"

#[[menu.main]]
#    name       = "Option 4: Agency"
#    url        = "/"
#    weight     = 4
#    parent     = "menu.home"

#[[menu.main]]
#    name       = "Option 5: Portfolio"
#    url        = "/"
#    weight     = 5
#    parent     = "menu.home"

[[menu.main]]
    name       = "Platform"
    identifier = "platform"
    url        = "/platform/"
    weight     = 2

[[menu.main]]
    name       = "Volunteer"
    identifier = "volunteer"
    url        = "https://docs.google.com/forms/d/1cSOd6QLZUqIqVszRTsG-xNuEN437lkDN6pqRilvj8m8"
    weight     = 3

#[[menu.main]]
#    name       = "Blog"
#    identifier = "menu.blog"
#    url        = "/blog/"
#    weight     = 5

#[[menu.main]]
#    name       = "FAQ"
#    identifier = "menu.faq"
#    url        = "/faq/"
#    weight     = 6

#[[menu.main]]
#    identifier = "contact"
#    name       = "Contact"
#    url        = "/contact/"
#    weight     = 7


# Top bar social links menu

#[[menu.topbar]]
#    weight = 1
#    name = "Phone"
#    url = "tel:+12 34 567 89 01"
#    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "Instagram"
    url = "https://www.instagram.com/progressiveparty_usa"
    pre = "<i class='fab fa-2x fa-instagram'></i>"

[[menu.topbar]]
    weight = 3
    name = "Tiktok"
    url = "https://www.tiktok.com/@sydney4america"
    pre = "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 448 512'><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d='M448 209.9a210.1 210.1 0 0 1 -122.8-39.3V349.4A162.6 162.6 0 1 1 185 188.3V278.2a74.6 74.6 0 1 0 52.2 71.2V0l88 0a121.2 121.2 0 0 0 1.9 22.2h0A122.2 122.2 0 0 0 381 102.4a121.4 121.4 0 0 0 67 20.1z'/></svg>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "https://twitter.com/PPOA2040"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Mastodon"
    url = "https://mastodon.social/@PPOA"
    pre = "<i class='fab fa-2x fa-mastodon'></i>"

[[menu.topbar]]
    weight = 6
    name = "Bluesky"
    url = "https://bsky.app/profile/ppoa.bsky.social"
    pre = "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 576 512'><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d='M407.8 294.7c-3.3-.4-6.7-.8-10-1.3c3.4 .4 6.7 .9 10 1.3zM288 227.1C261.9 176.4 190.9 81.9 124.9 35.3C61.6-9.4 37.5-1.7 21.6 5.5C3.3 13.8 0 41.9 0 58.4S9.1 194 15 213.9c19.5 65.7 89.1 87.9 153.2 80.7c3.3-.5 6.6-.9 10-1.4c-3.3 .5-6.6 1-10 1.4C74.3 308.6-9.1 342.8 100.3 464.5C220.6 589.1 265.1 437.8 288 361.1c22.9 76.7 49.2 222.5 185.6 103.4c102.4-103.4 28.1-156-65.8-169.9c-3.3-.4-6.7-.8-10-1.3c3.4 .4 6.7 .9 10 1.3c64.1 7.1 133.6-15.1 153.2-80.7C566.9 194 576 75 576 58.4s-3.3-44.7-21.6-52.9c-15.8-7.1-40-14.9-103.2 29.8C385.1 81.9 314.1 176.4 288 227.1z'/></svg>"
[[menu.topbar]]
    weight = 7
    name = "Reddit"
    url = "https://www.reddit.com/r/USAprogressiveparty"
    pre = "<i class='fab fa-2x fa-reddit'></i>"
[[menu.topbar]]
    weight = 8
    name = "Discord"
    url = "https://discord.gg/5gmTgZT4Qg"
    pre = "<i class='fab fa-2x fa-discord'></i>"

#[[menu.topbar]]
#    weight = 9
#    name = "Facebook"
#    url = ""
#    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 10
    name = "Email"
    url = "mailto:sydney@progressivepartyofamerica.us"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Progressive Party of America"
    defaultKeywords = ["Progressive Party of America", "US political party", "grassroots movement", "For the People", "From Corporate Greed to Human Need", "#FromCorporateGreedtoHumanNeed", "Sydney4America"]
    mainSections = ["blog"]
    defaultDescription = "Dedicated to making life, liberty, and the pursuit of happiness available to everyone. From Corporate Greed to Human Need."

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "PPOA2040" # the Twitter handle of your site (without the '@')
    default_sharing_image = "/images/its_time_for_change.jpg"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Dedicated to making life, liberty, and the pursuit of happiness available to everyone. From Corporate Greed to Human Need.</p>"
    copyright = "Copyright (c) 2024 - 2040, Progressive Party of America; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Progressive Party of America"

    logo = "/images/green_icon.png"
    logo_small = "/images/pro_green.png"
    contact_url = "/contact"
#    address = """<p class="text-uppercase"><strong>Universal Ltd.</strong>
#        <br>13/25 New Avenue
#        <br>Newtown upon River
#        <br>45Y 73J
#        <br>England
#        <br>
#        <strong>Great Britain</strong>
#      </p>
#      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = ""
#    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
#      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
#      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
#      </p>
#      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 1
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 1
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = false
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = ""
    hide_summary = true

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
